pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp *.html public/ || true
    - cp *.css public/ || true
    - cp *.js public/ || true
    - cp *.xlsx public/ || true
  artifacts:
    paths:
      - public
  only:
    - master
